baseURL = 'http://fragkoudakis.gr'
languageCode = 'en'
title = "Christodoulos Fragkoudakis"

[author]
name = "Christodoulos Fragkoudakis"
image = "img/me.jpg"
headline = "Welcome to my homepage"
bio = "A nerd, too old to grow up"
links = [
{ github = "https://github.com/christodoulos"},
{ linkedin = "https://www.linkedin.com/in/fragkoudakis/"},
{ twitter = "https://twitter.com/CFragkoudakis"},
{ facebook = "https://www.facebook.com/christodoulos.fragkoudakis/"},
]

