colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true
footer.showAppearanceSwitcher = true

enableSearch = false
enableCodeCopy = true
css=["custom.css"]

# mainSections = ["section1", "section2"]
# robots = ""
footer.showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = true

[article]
showTaxonomies = true
showTableOfContents = true
showDateUpdated = true
