colorScheme = "congo"
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true
showAppearanceSwitcher = false

enableSearch = false
enableCodeCopy = true

# mainSections = ["section1", "section2"]
# robots = ""
showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, custom
  showRecent = false

