url: "https://fragkoudakis.gr" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Christodoulos Fragkoudakis" # the name of your site, e.g. ACME Corp.

plugins:
  - jekyll-postcss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - tailwind.config.js
  - netlify.toml
  - bin
  - .gitignore
  - .stylelintrc.json
